# Generated by Django 2.2 on 2022-05-20 13:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220512_1519'),
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='description',
        ),
        migrations.AddField(
            model_name='painting',
            name='additional_info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='adivasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('as', 'Assamese'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('lus', 'Mizo'), ('or', 'Odia'), ('pa', 'Punjabi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('fr', 'French'), ('ge', 'German'), ('hne', 'Chhattisgarhi')], default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='occupation',
            field=models.CharField(blank=True, help_text='Enter the occupation of the person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='occupation_of_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='original_image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_image_1', to='core.AffixImage'),
        ),
        migrations.AddField(
            model_name='painting',
            name='quote',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location', verbose_name='Place of Origin'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
    ]
