# Generated by Django 2.2 on 2022-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_author_bio_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_hne',
            field=models.TextField(blank=True, null=True),
        ),
    ]
