# Generated by Django 2.2.28 on 2023-01-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_author_bio_hne'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_bho',
            field=models.TextField(blank=True, null=True),
        ),
    ]
