# Generated by Django 2.2 on 2022-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_author_bio_hne'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_hin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
