# Generated by Django 2.2 on 2022-05-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_author_bio_hin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio_hin',
            new_name='bio_ge',
        ),
    ]
