# Generated by Django 2.2.28 on 2023-01-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0015_albumslide_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('as', 'Assamese'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('lus', 'Mizo'), ('or', 'Odia'), ('pa', 'Punjabi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('hne', 'Chhattisgarhi'), ('bho', 'Bhojpuri')], max_length=7),
        ),
    ]
